# Generated by Django 3.2.7 on 2021-09-08 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Files',
        ),
    ]
